import java.time.Duration;
import java.time.Instant;

import ipn.SimpleAlert;
import ipn.TimeRemaining;
import kafka.IPNProducer;
/**
 * Dummy runner
 * @author dglachs
 *
 */
public class Main2 {
	public static void main(String[] args) {
		String groupId = "x";
		IPNProducer producer = new IPNProducer("ipn", "il061:9092,il062:9092,il063:9092", groupId);
		
		producer.sendAlert("Malfunctions", "alert", new SimpleAlert("This is a message generated by IPN inCARE").createPayload(2l, Instant.now()));
//		producer.sendAlert("Malfunctions", "remainingTime", new TimeRemaining(Duration.ofHours(30), 0.8d).createPayload(2l, Instant.now()));
		producer.shutdown();

	}

}
